tap "beeftornado/rmtree"
tap "buo/cask-upgrade"
tap "dart-lang/dart"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask", "https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-cask.git"
tap "homebrew/core", "https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git"
tap "homebrew/services"
tap "sass/sass"
brew "aria2"
brew "asciinema"
brew "autossh"
brew "python"
brew "curl"
brew "docker-compose"
brew "fd"
brew "ffmpeg"
brew "node"
brew "fx"
brew "fzf"
brew "gcc"
brew "gdrive"
brew "ghc"
brew "gifsicle"
brew "gist"
brew "git"
brew "gnupg"
brew "go"
brew "highlight"
brew "httpie"
brew "hugo"
brew "iperf"
brew "lnav"
brew "m-cli"
brew "mas"
brew "mycli"
brew "ncdu"
brew "neofetch"
brew "neovim"
brew "nmap"
brew "onefetch"
brew "protobuf"
brew "ranger"
brew "rename"
brew "ripgrep"
brew "shellcheck"
brew "tcpdump"
brew "telnet"
brew "tig"
brew "tldr"
brew "tmux"
brew "tree"
brew "unrar"
brew "w3m"
brew "yadm"
brew "yarn"
brew "youtube-dl"
brew "zsh"
brew "heroku/brew/heroku"
brew "sass/sass/sass"
cask "android-studio"
cask "appcleaner"
cask "clashx"
cask "dash"
cask "docker"
cask "firefox"
cask "hyper"
cask "iina"
cask "itsycal"
cask "java"
cask "keycastr"
cask "mactex-no-gui"
cask "marginnote"
cask "miniconda"
cask "numi"
cask "pycharm"
cask "snipaste"
cask "thunder"
cask "ticktick"
cask "typora"
cask "upic"
cask "visual-studio-code"
mas "Bitwarden", id: 1352778147
mas "GIPHY CAPTURE", id: 668208984
mas "iMovie", id: 408981434
mas "Magnet", id: 441258766
mas "Network & Battery", id: 1387780159
mas "Reeder", id: 880001334
mas "Telegram", id: 747648890
mas "Xcode", id: 497799835
