tap "beeftornado/rmtree"
tap "buo/cask-upgrade"
tap "cjbassi/gotop"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core", "https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git"
tap "homebrew/services"
tap "ringohub/redis-cli"
brew "aria2"
brew "openssl"
brew "python"
brew "asciinema"
brew "autossh"
brew "ffmpeg"
brew "node"
brew "fx"
brew "fzf"
brew "gcc"
brew "gdrive"
brew "ghc"
brew "gifsicle"
brew "gist"
brew "git"
brew "go"
brew "highlight"
brew "httpie"
brew "hugo"
brew "iperf"
brew "lnav"
brew "m-cli"
brew "mas"
brew "ncdu"
brew "neofetch"
brew "neovim"
brew "nmap"
brew "ranger"
brew "rename"
brew "ripgrep"
brew "shellcheck"
brew "tcpdump"
brew "telnet"
brew "tig"
brew "tldr"
brew "tmux"
brew "tree"
brew "unrar"
brew "yadm"
brew "yarn"
brew "youtube-dl"
brew "zsh"
brew "cjbassi/gotop/gotop"
brew "ringohub/redis-cli/redis-cli"
cask "appcleaner"
cask "clashx"
cask "font-cascadia"
cask "font-consolas-for-powerline"
cask "google-chrome"
cask "iina"
cask "itsycal"
cask "java"
cask "keycastr"
cask "mactex-no-gui"
cask "nextcloud"
cask "numi"
cask "snipaste"
cask "upic"
cask "virtualbox"
cask "visual-studio-code"
cask "wechatwebdevtools"
mas "iMovie", id: 408981434
mas "Magnet", id: 441258766
mas "Network & Battery", id: 1387780159
mas "Reeder", id: 880001334
mas "Telegram", id: 747648890
mas "Xcode", id: 497799835
