#!/bin/bash
set -ex

system_type=$(uname -s)

cd $HOME
echo "init submodules..."
yadm submodule update --recursive --init

function install_on_common() {
    npm config set prefix "${HOME}/.node_modules"
    npm config set registry "https://registry.npmmirror.com"

    if ! command -v cnpm > /dev/null 2>&1; then
        npm install -g cnpm --registry=https://registry.npm.taobao.org
    fi

    # vim plugins managed by vim-plug
    if command -v nvim > /dev/null 2>&1; then
        echo "Bootstrapingn Neovim..."
        nvim '+PlugInstall' '+PlugClean!' '+qall'
    fi
}


function install_on_macOS() {
    # install HomeBrew if it's missing.
    if ! command -v brew > /dev/null 2>&1; then
        echo "Installing HomeBrew..."
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi

    # install apps from Brewfile
    brew bundle -v -g
}


function install_on_ArchLinux() {
    # Change aur mirrors
    sudo curl -o /etc/pacman.d/mirrorlist "https://www.archlinux.org/mirrorlist/?country=CN&country=HK&country=US&protocol=http&protocol=https&ip_version=4&ip_version=6"
    sudo sed -i 's/#Server/Server/g' /etc/pacman.d/mirrorlist && pacman -Syyu --noconfirm
    sudo sed -i 's/#Color/Color/g' /etc/pacman.conf

    if ! command -v yay > /dev/null 2>&1; then
        # Installing yay
        echo "Install Yay..."
        rm -rf /tmp/yay && git clone --depth 1 https://aur.archlinux.org/yay.git /tmp/yay && cd /tmp/yay && makepkg -si --noconfirm
    fi

    echo "Installing from .Pacmanfile..."
    yay -S --needed --noconfirm - < $HOME/.Pacmanfile
}


case "$system_type" in
    "Darwin")
        install_on_macOS;;
    "Linux")
        install_on_ArchLinux;;
    *)
        echo "Cannot detect the system...";;
esac

install_on_common
