# Port of HTTP(S) proxy server on the local end
port: 7890

# Port of SOCKS5 proxy server on the local end
# socks-port: 7891

# Transparent proxy server port for Linux and macOS (Redirect TCP and TProxy UDP)
# redir-port: 7892

# Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
# tproxy-port: 7893

# HTTP(S) and SOCKS5 server on the same port
# mixed-port: 7890

# authentication of local SOCKS5/HTTP(S) server
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

# Set to true to allow connections to the local-end server from
# other LAN IP addresses
allow-lan: true

# This is only applicable when `allow-lan` is `true`
# '*': bind all IP addresses
# 192.168.122.11: bind a single IPv4 address
# "[aaaa::a8aa:ff:fe09:57d8]": bind a single IPv6 address
bind-address: '*'

# Clash router working mode
# rule: rule-based packet routing
# global: all packets will be forwarded to a single endpoint
# direct: directly forward the packets to the Internet
mode: rule

# Clash by default prints logs to STDOUT
# info / warning / error / debug / silent
log-level: info

# When set to false, resolver won't translate hostnames to IPv6 addresses
ipv6: false

# RESTful web API listening address
external-controller: 0.0.0.0:9090

# A relative path to the configuration directory or an absolute path to a
# directory in which you put some static web resource. Clash core will then
# serve it at `http://{{external-controller}}/ui`.
external-ui: yacd

# Secret for the RESTful API (optional)
# Authenticate by spedifying HTTP header `Authorization: Bearer ${secret}`
# ALWAYS set a secret if RESTful API is listening on 0.0.0.0
# secret: ""

# Static hosts for DNS server and connection establishment (like /etc/hosts)
#
# Wildcard hostnames are supported (e.g. *.clash.dev, *.foo.*.example.com)
# Non-wildcard domain names have a higher priority than wildcard domain names
# e.g. foo.example.com > *.example.com > .example.com
# P.S. +.foo.com equals to .foo.com and foo.com
hosts:
  # '*.clash.dev': 127.0.0.1
  # '.dev': 127.0.0.1
  # 'alpha.clash.dev': '::1'

profile:
  # store the `select` results in $HOME/.config/clash/.cache
  # when two different configurations have groups with the same name, the selected values are shared
  # set false if you don't want this behavior
  store-selected: true

dns:
  enable: true
  listen: 0.0.0.0:53

  default-nameserver:
    - 114.114.114.114
    - 1.1.1.1

  nameserver:
    - 114.114.114.114
    - 1.1.1.1

proxy-groups:
  - name: Proxy
    type: select
    use:
      - linkhub
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

  - name: Apple
    type: select
    use:
      - linkhub
    proxies:
      - DIRECT

proxy-providers:
  linkhub:
    type: http
    url: '{{ your_proxy_url }}'
    interval: 3600
    path: ./proxies/linkhub.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

rules:
  - IP-CIDR,       10.0.0.0/8,     DIRECT
  - IP-CIDR,       17.0.0.0/8,     DIRECT
  - IP-CIDR,       100.64.0.0/10,  DIRECT
  - IP-CIDR,       127.0.0.0/8,    DIRECT
  - IP-CIDR,       172.16.0.0/12,  DIRECT
  - IP-CIDR,       192.168.0.0/16, DIRECT
  - DOMAIN-SUFFIX, local,          DIRECT
  - DOMAIN-SUFFIX, localhost,      DIRECT

  # Apple
  - DOMAIN,        audio-ssl.itunes.apple.com, Apple
  - DOMAIN,        gspe1-ssl.ls.apple.com,     Apple
  - DOMAIN,        itunes.apple.com,           Apple
  - DOMAIN-SUFFIX, aaplimg.com,                Apple
  - DOMAIN-SUFFIX, apple.co,                   Apple
  - DOMAIN-SUFFIX, apple.com,                  Apple
  - DOMAIN-SUFFIX, appstore.com,               Apple
  - DOMAIN-SUFFIX, cdn-apple.com,              Apple
  - DOMAIN-SUFFIX, crashlytics.com,            Apple
  - DOMAIN-SUFFIX, icloud-content.com,         Apple
  - DOMAIN-SUFFIX, icloud.com,                 Apple
  - DOMAIN-SUFFIX, itunes.apple.com,           Apple
  - DOMAIN-SUFFIX, me.com,                     Apple
  - DOMAIN-SUFFIX, mzstatic.com,               Apple
  - DOMAIN-SUFFIX, icloud.com.cn,              Apple
  - DOMAIN-SUFFIX, apple.cn,                   Apple

  # Twitter
  - DOMAIN-SUFFIX, t.co,        Proxy
  - DOMAIN-SUFFIX, twimg.co,    Proxy
  - DOMAIN-SUFFIX, twimg.com,   Proxy
  - DOMAIN-SUFFIX, twitpic.com, Proxy
  - DOMAIN-SUFFIX, twitter.com, Proxy

  # Telegram
  - IP-CIDR,       67.198.55.0/24,   Proxy
  - IP-CIDR,       91.108.0.0/16,    Proxy
  - IP-CIDR,       109.239.140.0/24, Proxy
  - IP-CIDR,       149.154.160.0/20, Proxy
  - IP-CIDR,       205.172.60.0/22,  Proxy
  - DOMAIN-SUFFIX, t.me,             Proxy
  - DOMAIN-SUFFIX, tdesktop.com,     Proxy
  - DOMAIN-SUFFIX, telegra.ph,       Proxy
  - DOMAIN-SUFFIX, telegram.me,      Proxy
  - DOMAIN-SUFFIX, telegram.org,     Proxy
  - DOMAIN-SUFFIX, telesco.pe,       Proxy

  # Mirrors
  #
  - DOMAIN-SUFFIX, bitwarden.com, Proxy
  - DOMAIN-SUFFIX, bitwarden.net, Proxy

  - DOMAIN-SUFFIX, dytt8.net,    DIRECT
  - DOMAIN-SUFFIX, ipstack.com,  DIRECT
  - DOMAIN-SUFFIX, qq.com,       DIRECT
  - DOMAIN-SUFFIX, dingtalk.com, DIRECT
  - DOMAIN-SUFFIX, autonavi.com, DIRECT
  - DOMAIN-SUFFIX, amap.com,     DIRECT

  # AdBlocks
  - DOMAIN-SUFFIX, rayjump.com, REJECT

  - GEOIP, CN, DIRECT
  - MATCH, Proxy
