#!/bin/bash

NC='\033[0m'
GREEN='\033[0;32m'
RED='\033[0;31m'

# install packages from pypi
PYPI_PACKAGES="mycli paramiko bpython pynvim unidecode"

# replace node_modules
case $(uname) in
    "Darwin")
        sed -i "" -e "s#prefix=.*#prefix=${HOME}/.node_modules#" ${HOME}/.npmrc
        sed -i "" -e "s#/Users/vast/#${HOME}#" ${HOME}/.npmrc
        sed -i "" -e "s#/Users/vastpeng/#${HOME}/#" ${HOME}/.aria2/aria2.conf
        pip3 install ${PYPI_PACKAGES}
        ;;
    "Linux")
        sed -i -e "s#prefix=.*#prefix=${HOME}/.node_modules#" ${HOME}/.npmrc
        sed -i -e "s#/Users/vast/#${HOME}#" ${HOME}/.npmrc
        sed -i "" -e "s#/Users/vastpeng/#${HOME}/#" ${HOME}/.aria2/aria2.conf
        # pacman -Qqen > $HOME/.Pacmanfile
        yay -S - < $HOME/.Pacmanfile
        sudo pip3 install ${PYPI_PACKAGES}
        ;;
    *)
        ;;
esac

